
log:
  dir: ""


clients:
  - name: ночлежка
    type: вк
    url: https://mks.homeless.ru
    endpoint: app/version
  - name: перспективы
    type: яндекс
    url: https://mks.perspektivy.ru
    endpoint: app/version
  - name: новое начало
    type: вк
    url: https://xn--j1adq.xn--80aaem6ahcfbf0h.xn--p1ai
    endpoint: app/version

# https://mks.ossne.ru/login
