log:
  dir: ""

allowed_users:
  - kvendingoldo
  - nikolai_mishin
  - yakovenko_sv
  - pangurbano
  - TurangaLipina
  - amenshchikov
  - eramonstera
  - bulgkate
  - chelseadagger
  - satamas
  - mariia_lobanova
  - dkramorov
  - Roman_Verkhovkii

clients:
  - name: ночлежка тест
    type: вк
    url: mks.homeless.ru

  - name: БФ "Ковчег"
    type: вк
    url: mks.ossne.ru

  - name: БФ "Люблю и благодарю"
    type: вк
    url: mks.libfund.ru

  - name: Рука помощи43
    type: вк
    url: mks.helpinghand43.ru

  - name: новое начало
    type: вк
    url: xn--j1adq.xn--80aaem6ahcfbf0h.xn--p1ai

  - name: АНО Эпоха Водолея
    type: вк
    url: mks.iznanka.info

  - name: перспективы
    type: яндекс
    url: mks.perspektivy.ru

  - name: маяк
    type: яндекс
    url: mks.stophomelessness.ru

  - name: Милосердие и забота
    type: вк
    url: xn--j1adq.xn-----8kcaeogbuecc7am6akyq5a.xn--p1ai

  - name: ТЫ ДОМА
    type: вк
    url: mks.td-samara.ru

  - name: Жить вместе
    type: вк
    url: mks.zhitvmeste.ru
